### ISSUE TITLE
Daily check

### ISSUE THREAD

**Issue by sojjan1337** [binbashar/terraform-aws-cost-billing-alarm#17]
Hi!

Is it possible to have a daily period instead of monthly.

daily_billing_threshold

https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-estimatedcharges-alarm/

Thanks!

**Comment by exequielrafaela** [comment]
Hey @sojjan1337 thanks for your feature requests. We'll evaluate the feasibility with the team and come with an answer as soon as we can. 

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev

**Comment by exequielrafaela** [comment]
@sojjan1337 So is this feature not needed any more?
